/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type JobApplication = {
  _id: string;
  _type: "jobApplication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  submittedAt?: string;
  notificationStatus?: "pending" | "sent" | "failed" | "disabled";
  status?: "new" | "inProgress" | "closed";
  retentionUntil?: string;
  anonymizedAt?: string;
  internalNotes?: string;
  job?: string;
  birthDate?: string;
  gender?: string;
  maritalStatus?: string;
  address?: string;
  preferredBrand?: string;
  startDate?: string;
  salary?: string;
  education?: string;
  experience?: string;
  employer?: string;
  note?: string;
  cv?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type FranchiseSubmission = {
  _id: string;
  _type: "franchiseSubmission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  submittedAt?: string;
  notificationStatus?: "pending" | "sent" | "failed" | "disabled";
  status?: "new" | "inProgress" | "closed";
  retentionUntil?: string;
  anonymizedAt?: string;
  internalNotes?: string;
  city?: string;
  investment?: string;
  brand?: string;
  message?: string;
  customFields?: Array<{
    key?: string;
    value?: string;
    _key: string;
  }>;
};

export type ContactSubmission = {
  _id: string;
  _type: "contactSubmission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  submittedAt?: string;
  notificationStatus?: "pending" | "sent" | "failed" | "disabled";
  status?: "new" | "inProgress" | "closed";
  retentionUntil?: string;
  anonymizedAt?: string;
  internalNotes?: string;
  subject?: string;
  message?: string;
};

export type Job = {
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
  department?: LocalizedString;
  employmentType?: LocalizedString;
  description?: LocalizedText;
  responsibilities?: LocalizedBlockContent;
  requirements?: LocalizedBlockContent;
  publishedAt?: string;
  expiresAt?: string;
  active?: boolean;
};

export type LocalizedBlockContent = {
  _type: "localizedBlockContent";
  ar?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  en?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type LocalizedText = {
  _type: "localizedText";
  ar?: string;
  en?: string;
};

export type LocalizedString = {
  _type: "localizedString";
  ar?: string;
  en?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type NewsCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "newsCategory";
};

export type NewsArticle = {
  _id: string;
  _type: "newsArticle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
  excerpt?: LocalizedText;
  body?: LocalizedBlockContent;
  category?: NewsCategoryReference;
  publishedAt?: string;
  image?: ImageWithAlt;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: LocalizedString;
  description?: LocalizedText;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: LocalizedString;
};

export type NewsCategory = {
  _id: string;
  _type: "newsCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocalizedString;
  role?: LocalizedString;
  photo?: ImageWithAlt;
  order?: number;
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type Branch = {
  _id: string;
  _type: "branch";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocalizedString;
  slug?: Slug;
  brand?: BrandReference;
  district?: LocalizedString;
  side?: LocalizedString;
  address?: LocalizedText;
  location?: Geopoint;
  mapX?: number;
  mapY?: number;
  phone?: string;
  hours?: LocalizedText;
  active?: boolean;
  order?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Division = {
  _id: string;
  _type: "division";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocalizedString;
  slug?: Slug;
  description?: LocalizedText;
  image?: ImageWithAlt;
  order?: number;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocalizedString;
  slug?: Slug;
  category?: LocalizedString;
  description?: LocalizedText;
  website?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  image?: ImageWithAlt;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  active?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type NewsPage = {
  _id: string;
  _type: "newsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  hero?: PageHero;
  seo?: Seo;
};

export type PageHero = {
  _type: "pageHero";
  eyebrow?: LocalizedString;
  title?: LocalizedString;
  description?: LocalizedText;
  image?: ImageWithAlt;
};

export type ApplicationPage = {
  _id: string;
  _type: "applicationPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  hero?: PageHero;
  seo?: Seo;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  hero?: PageHero;
  formHeading?: LocalizedString;
  formDescription?: LocalizedText;
  seo?: Seo;
};

export type CareersPage = {
  _id: string;
  _type: "careersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  hero?: PageHero;
  culture?: ContentBlock;
  cultureValues?: Array<
    {
      _key: string;
    } & LocalizedString
  >;
  benefitsHeading?: LocalizedString;
  benefits?: Array<
    {
      _key: string;
    } & FeatureItem
  >;
  positionsHeading?: LocalizedString;
  callToAction?: ContentBlock;
  callToActionLabel?: LocalizedString;
  seo?: Seo;
};

export type ContentBlock = {
  _type: "contentBlock";
  heading?: LocalizedString;
  body?: LocalizedText;
  image?: ImageWithAlt;
};

export type FranchisePage = {
  _id: string;
  _type: "franchisePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  hero?: PageHero;
  featuresHeading?: LocalizedString;
  features?: Array<
    {
      _key: string;
    } & FeatureItem
  >;
  formHeading?: LocalizedString;
  formDescription?: LocalizedText;
  formFields?: Array<
    {
      _key: string;
    } & FormFieldDefinition
  >;
  seo?: Seo;
};

export type BrandsPage = {
  _id: string;
  _type: "brandsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  hero?: PageHero;
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  hero?: PageHero;
  introduction?: ContentBlock;
  statistics?: Array<
    {
      _key: string;
    } & Stat
  >;
  historyHeading?: LocalizedString;
  timeline?: Array<
    {
      _key: string;
    } & TimelineItem
  >;
  vision?: ContentBlock;
  mission?: ContentBlock;
  teamHeading?: LocalizedString;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  heroSlides?: Array<{
    eyebrow?: LocalizedString;
    title?: LocalizedString;
    image?: ImageWithAlt;
    _key: string;
  }>;
  introduction?: ContentBlock;
  introductionFacts?: Array<
    {
      _key: string;
    } & Stat
  >;
  statistics?: Array<
    {
      _key: string;
    } & Stat
  >;
  divisionsHeading?: LocalizedString;
  brandsHeading?: LocalizedString;
  branchesHeading?: LocalizedString;
  branchesDescription?: LocalizedText;
  newsHeading?: LocalizedString;
  brandFocusHeading?: LocalizedString;
  sustainability?: ContentBlock;
  sustainabilityFacts?: Array<
    {
      _key: string;
    } & Stat
  >;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyName?: LocalizedString;
  address?: LocalizedText;
  phone?: string;
  email?: string;
  franchiseEmail?: string;
  careersEmail?: string;
  secondaryPhone?: string;
  workingHours?: LocalizedString;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  defaultSeo?: Seo;
};

export type FormFieldDefinition = {
  _type: "formFieldDefinition";
  key?: string;
  label?: LocalizedString;
  type?: "text" | "email" | "tel" | "number" | "select" | "textarea";
  placeholder?: LocalizedString;
  options?: Array<
    {
      _key: string;
    } & LocalizedString
  >;
  required?: boolean;
  fullWidth?: boolean;
};

export type TimelineItem = {
  _type: "timelineItem";
  year?: string;
  title?: LocalizedString;
  description?: LocalizedText;
};

export type FeatureItem = {
  _type: "featureItem";
  icon?: string;
  title?: LocalizedString;
  description?: LocalizedText;
};

export type Stat = {
  _type: "stat";
  value?: string;
  label?: LocalizedString;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SanityFileAssetReference
  | JobApplication
  | FranchiseSubmission
  | ContactSubmission
  | Job
  | LocalizedBlockContent
  | LocalizedText
  | LocalizedString
  | Slug
  | NewsCategoryReference
  | NewsArticle
  | SanityImageAssetReference
  | Seo
  | ImageWithAlt
  | NewsCategory
  | TeamMember
  | BrandReference
  | Branch
  | Geopoint
  | Division
  | Brand
  | SanityImageCrop
  | SanityImageHotspot
  | NewsPage
  | PageHero
  | ApplicationPage
  | ContactPage
  | CareersPage
  | ContentBlock
  | FranchisePage
  | BrandsPage
  | AboutPage
  | HomePage
  | SiteSettings
  | FormFieldDefinition
  | TimelineItem
  | FeatureItem
  | Stat
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;
