import {
  localizedString,
  localizedText,
  localizedBlockContent,
  seo,
  imageWithAlt,
  stat,
  pageHero,
  contentBlock,
  featureItem,
  timelineItem,
  formFieldDefinition,
  jobFormFieldDefinition,
} from "./shared";
import {
  siteSettings,
  homePage,
  aboutPage,
  brandsPage,
  franchisePage,
  careersPage,
  contactPage,
  applicationPage,
  newsPage,
  brand,
  division,
  branch,
  teamMember,
  newsCategory,
  newsArticle,
  job,
} from "./documents";
import {
  contactSubmission,
  franchiseSubmission,
  jobApplication,
  rateLimitBucket,
} from "./submissions";
export const schemaTypes = [
  localizedString,
  localizedText,
  localizedBlockContent,
  seo,
  imageWithAlt,
  stat,
  pageHero,
  contentBlock,
  featureItem,
  timelineItem,
  formFieldDefinition,
  jobFormFieldDefinition,
  siteSettings,
  homePage,
  aboutPage,
  brandsPage,
  franchisePage,
  careersPage,
  contactPage,
  applicationPage,
  newsPage,
  brand,
  division,
  branch,
  teamMember,
  newsCategory,
  newsArticle,
  job,
  contactSubmission,
  franchiseSubmission,
  jobApplication,
  rateLimitBucket,
];
